# Site
repository: Yidesdo97/Yidesdo97.github.io
# Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Yiyuan Pu (Gracie)
title: PhD (Graduating in Jan, 2025)
email: yiyuanpu.unimelb@gmail.com
# email_title: Email (Email title override)
phone_title: Wechat
phone: 15618068621
# website: yidesdo97.github.io
# website_title: Wechat
# website: 15618068621



# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: jekyllrb
# github_username:  Yidesdo97
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jekyll
# linkedin_username: Gracie Pu
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: jekyll
orcid_username: 0000-0002-0814-8312
googlescholar_username: Yiyuan Pu

# Additional icon links
# additional_links:
# - title: Link name
#   icon: Font Awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/IMG_8480.jpg
# Images ![alt text](/images/IMG_8480.jpg)
about_content: | # this will include new lines to allow paragraphs
  I am a PhD candidate at the [ARC Training Centre in Cognitive Computing for Medical Technologies](https://aimedtech.org.au/) at the University of Melbourne, where I am in the <mark>final six months</mark> of my doctoral studies. My thesis focuses on Literature-Based Discovery (LBD) for Alzheimer’s Disease (AD), supervised by [Prof Karin Verspoor](https://scholar.google.com/citations?user=dUxHnbcAAAAJ&hl=en), [Dr Daniel Beck](https://scholar.google.com/citations?user=NauI6dEAAAAJ&hl=en), and [Dr Michael Conway](https://scholar.google.com.au/citations?user=uiJso6MAAAAJ&hl=en). I am also in close collaboration with the University of Edinburgh at the [AD-SOLES project](https://www.ed.ac.uk/clinical-brain-sciences/research/camarades/research-portfolio/current-projects) with [Dr Kaitlyn Hair](https://scholar.google.com/citations?user=f3fWQWMAAAAJ&hl=en) and [Prof Malcolm Macleod](https://scholar.google.co.uk/citations?user=_cLoK0sAAAAJ&hl=en).
  
  My thesis aims to predict and validate previously unknown knowledge for Alzheimer’s Disease using LBD methodologies. The study is motivated by the exponential growth of AD research findings and the complexity of AD at both molecular and clinical levels, which present significant challenges in identifying, extracting, and synthesizing pathological processes and clinical symptoms. LBD methodologies aim to reduce information overload and provide valuable insights into disease diagnosis, treatments, and mechanisms.

  I am looking for <mark>full-time opportunities<\mark> and open to relocation.
  Interested areas include but not limited to: <mark>Natural language processing, large language models, and NLP applications<\mark>.

content:
  - title: Papers # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: BioNLP 2024 and Shared Tasks @ ACL 2024
        link: tbd
        # link_text: tbd
        # additional_links:
        #   - title:  Github page for project (eg. sproogen/modern-resume-theme)
        #     icon: fab fa-github
        #     url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        #   - title:  Github page for project (eg. sproogen/modern-resume-theme)
        #     icon: fab fa-github
        #     url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        quote: >
          Intervention extraction in preclinical animal studies of Alzheimer’s Disease
        description: | # this will include new lines to allow paragraphs
          We explore different information extraction tools for annotation of interventions to support automated systematic reviews of preclinical AD animal studies. We compare two PICO (Population, Intervention, Comparison, and Outcome) extraction tools and two prompting-based learning strategies based on Large Language Models (LLMs). Motivated by the high recall of a dictionary-based approach, we define a two-stage method, removing false positives obtained from regexes with a pre-trained LM. With ChatGPT-based filtering using three-shot prompting, our approach reduces almost two-thirds of False Positives compared to the dictionary approach alone, while outperforming knowledge-free instructional prompting.
      - layout: left
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: Journal of Biomedical Informatics
        link: [Paper link](https://www.sciencedirect.com/science/article/pii/S1532046423001855)
        # link_text: tbd
        additional_links:
          - title:  READ-BioMed/readbiomed-lbd
          # (eg. sproogen/modern-resume-theme)
            icon: fab fa-github
            url: https://github.com/READ-BioMed/readbiomed-lbd
        #   - title:  Github page for project (eg. sproogen/modern-resume-theme)
        #     icon: fab fa-github
        #     url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        quote: >
          Graph embedding-based link prediction for literature-based discovery in Alzheimer’s Disease 
        description: | # this will include new lines to allow paragraphs
          We explore the framing of literature-based discovery (LBD) as link prediction and graph embedding learning, with Alzheimer’s Disease (AD) as our focus disease context. The key link prediction setting of prediction window length is specifically examined in the context of a time-sliced evaluation methodology. We propose a four-stage approach to explore literature-based discovery for Alzheimer’s Disease, creating and analyzing a knowledge graph tailored to the AD context, and predicting and evaluating new knowledge based on time-sliced link prediction. Neural network graph-embedding link prediction methods show promise for the literature-based discovery context, although the prediction setting is extremely challenging, with graph densities of less than 1%. Varying prediction window length on the time-sliced evaluation methodology leads to hugely different results and interpretations of LBD studies. 
      - layout: left
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: Journal of Biomedical Semantics (preprint)
        link: tbd
        # link_text: tbd
        # additional_links:
        #   - title:  READ-BioMed/readbiomed-lbd
        #   # (eg. sproogen/modern-resume-theme)
        #     icon: fab fa-github
        #     url: https://github.com/READ-BioMed/readbiomed-lbd
        #   - title:  Github page for project (eg. sproogen/modern-resume-theme)
        #     icon: fab fa-github
        #     url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        quote: >
          Enriched knowledge representation in biological fields: A case study of Literature-based Discovery in Alzheimer’s Disease, preprint in Journal of Biomedical Semantics
        description: | # this will include new lines to allow paragraphs
          We argue that the standard entity-based knowledge graph has important limitations for biological knowledge representation. We demonstrate the negative impacts of relying solely on pairwise relationships as representation strategies by using Literature-Based Discovery (LBD) as a case study. However, pairwise relationships adopted in a standard knowledge graph are essential in knowledge representation for LBD. These limitations can be mitigated by integrating more semantically complex knowledge representation strategies, including capturing collective interactions and allowing for nested entities. The use of more sophisticated knowledge representation will benefit biological fields with more expressive knowledge graphs. A downstream task of knowledge graph, such as LBD, can be benefitted as well, allowing for generation of implicit knowledge discoveries and explanations for disease diagnosis, treatment, and mechanism that are more biologically meaningful.

  - title: Education
    layout: list
    content:
      - layout: top-right
        title: University of Melbourne
        sub_title: Doctor of Philosophy
        caption: 2021.06 - present 
        quote: >
          Field of study: Natural Language Processing
        # description: | # this will include new lines to allow paragraphs
        #   Description of qualification
      - layout: top-right
        title: The University of British Columbia
        sub_title: Master of Data Science
        caption: 2019.09 - 2020.08
        quote: >
          Field of study: Computational Linguistics
        # description: | # this will include new lines to allow paragraphs
        #   Description of qualification

  # - title: Experience
  # - title: Activities
  #   layout: list
  #   content:
  #     - layout: right
  #       title: Company name
  #       sub_title: Job title
  #       caption: Date Range (eg. November 2016 - present)
  #       link: Link to company (optional)
  #       quote: >
  #         Short description of the company (optional)
  #       description: | # this will include new lines to allow paragraphs
  #         Description of role

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      I enjoy dancing when I am not doing research :)
      Images ![alt text](/images/IMG_8480.jpg)

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
